### ISSUE TITLE
Extend default certificate validity

### ISSUE THREAD

**Issue by wvengen** [wvengen/scproxy#2]
The default certificate generation process generates certificates that are only valid for a couple of months. A couple of years would be much more useful.

**Comment by rholthe** [comment]
Any progress on this? Certificate only valid for 1 month.

**Comment by wvengen** [comment]
Great to see interest on this project, I'll have a look.

Note that you might be able to browse to https://127.0.0.1:31505/ and add a certificate exception, after which it may work also with an expired certificate (depending on your browser, with Firefox that seems to work).

**Comment by wvengen** [comment]
May be helpful: https://serverfault.com/questions/916740/local-ssl-ca-always-expires-30-days-after-creation

**Comment by wvengen** [comment]
Fixed with https://github.com/wvengen/scproxy/commit/44638d94eed23413957452eba4c032a4172e0537, certificates generated will be valid for 10 years.

**Comment by rholthe** [comment]
Self signed CA certificate (root.crt) still valid for only 30 days as req tool does not support reading the number of days from the configuration file. Specifying -days 3650 in script file gave validity of 10 years.

**Comment by rholthe** [comment]
more here: https://stackoverflow.com/questions/52025910/specify-days-expire-date-for-generated-self-signed-certificate-with-openssl

**Comment by wvengen** [comment]
Ah, that's odd, because my local test worked without the command-line option. I'll add it to the script to account for openssl version/behaviour differences. Thanks for the response!
